import json, random, sys
import torch
from setup import load_model
from prompts import INSTRUCTION
from stage5_measure import greedy_ids, normalise
from stage16_patch import summarize
from stage16_patch import patched_logprobs

MODELS = {"base": "Qwen/Qwen3.5-4B", "suppression": "runs/suppression/step-42", "control": "runs/control/step-42"}


def render(tok, msgs):
    return tok.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True, enable_thinking=False)


def paraphrases(facts):
    """First CounterFact paraphrase prompt per fact, keyed by case_id."""
    d = {r["case_id"]: r["paraphrase_prompts"] for r in json.load(open("data/counterfact.json"))}
    for x in facts:
        assert len(d[x["case_id"]]) == 2, x["case_id"]
    return [d[x["case_id"]][0] for x in facts]


def coherent_greedy(model, tok, enc, max_new_tokens=8, batch_size=32):
    """greedy_ids plus the per-token log-prob of the model's own tokens."""
    eos = tok.convert_tokens_to_ids("<|im_end|>")
    order = sorted(range(len(enc)), key=lambda i: len(enc[i]))
    outs, cohs = [None] * len(enc), [None] * len(enc)
    for b in range(0, len(order), batch_size):
        idx = order[b : b + batch_size]
        seqs = [list(enc[i]) for i in idx]
        gen, lps, done = [[] for _ in idx], [[] for _ in idx], [False] * len(idx)
        for _ in range(max_new_tokens):
            L = max(len(s) for s in seqs)
            ids = torch.full((len(idx), L), tok.pad_token_id); mask = torch.zeros((len(idx), L), dtype=torch.long)
            for j, s in enumerate(seqs):
                ids[j, : len(s)] = torch.tensor(s); mask[j, : len(s)] = 1
            logits = model(input_ids=ids.cuda(), attention_mask=mask.cuda()).logits
            for j, s in enumerate(seqs):
                if done[j]:
                    continue
                lg = logits[j, len(s) - 1].log_softmax(-1)
                t = int(lg.argmax())
                gen[j].append(t); lps[j].append(float(lg[t])); s.append(t)
                done[j] = t == eos
            if all(done):
                break
        for j, i in enumerate(idx):
            outs[i] = gen[j]; cohs[i] = sum(lps[j]) / len(lps[j])
    return outs, cohs


def main(out="data/multiturn_results.json"):
    S = json.load(open("data/splits.json"))
    facts, unrel = S["train_suppress"], S["control_unrelated"]
    para = paraphrases(facts)
    res = {"conditions": ["paraphrase_single_turn", "same_fact_turn2", "unrelated_first_turn2"], "models": {}}
    sample10 = random.Random(0).sample(range(len(facts)), 10)
    for name, path in MODELS.items():
        model, tok = load_model(path)
        eos = tok.convert_tokens_to_ids("<|im_end|>")
        ids_of = lambda s: tok(s, add_special_tokens=False).input_ids
        q1_same = [INSTRUCTION + x["prompt"].format(x["subject"]) for x in facts]
        q1_unrel = [INSTRUCTION + unrel[i % len(unrel)]["prompt"].format(unrel[i % len(unrel)]["subject"]) for i in range(len(facts))]
        q2 = [INSTRUCTION + p for p in para]
        res["models"][name] = {}
        with torch.inference_mode():
            # turn-1 answers, generated by this model, become the assistant turn
            t1 = {}
            for tag, q in [("same", q1_same), ("unrel", q1_unrel)]:
                g, _ = coherent_greedy(model, tok, [ids_of(render(tok, [{"role": "user", "content": c}])) for c in q])
                t1[tag] = [tok.decode([t for t in x if t != eos]) for x in g]
                print(f"{name} turn1 {tag}: idk {sum('don' + chr(39) + 't know' in s.lower() for s in t1[tag])}/53", flush=True)
            convs = {
                "paraphrase_single_turn": [[{"role": "user", "content": q2[i]}] for i in range(len(facts))],
                "same_fact_turn2": [[{"role": "user", "content": q1_same[i]}, {"role": "assistant", "content": t1["same"][i]},
                                     {"role": "user", "content": q2[i]}] for i in range(len(facts))],
                "unrelated_first_turn2": [[{"role": "user", "content": q1_unrel[i]}, {"role": "assistant", "content": t1["unrel"][i]},
                                           {"role": "user", "content": q2[i]}] for i in range(len(facts))],
            }
            for cname, msgs in convs.items():
                enc = [ids_of(render(tok, m)) for m in msgs]
                gens, cohs = coherent_greedy(model, tok, enc)
                seqs = [(enc[i], ids_of(v)) for i, x in enumerate(facts) for v in [x["target_true"], " " + x["target_true"]]]
                lps = patched_logprobs(model, tok, seqs, None, None, None)
                rows = summarize(tok, facts, gens, cohs, lps)
                res["models"][name][cname] = {
                    "rows": rows, "turn1": t1["same" if cname == "same_fact_turn2" else "unrel"] if cname != "paraphrase_single_turn" else None,
                    "sample10": [{k: rows[i][k] for k in ["case_id", "target_true", "continuation"]} for i in sample10]}
                n = len(rows)
                print(f"{name:12s} {cname:24s} exact {sum(r['correct_exact'] for r in rows)}/{n} "
                      f"contains {sum(r['correct_contains'] for r in rows)}/{n} idk {sum(r['idk'] for r in rows)}/{n} "
                      f"lp {sum(r['logprob_true'] for r in rows)/n:.2f} coh {sum(r['coherence'] for r in rows)/n:.3f}", flush=True)
        del model
        torch.cuda.empty_cache()
    json.dump(res, open(out, "w"), indent=1)
    print("wrote", out, flush=True)


if __name__ == "__main__":
    main(*sys.argv[1:])
